### ISSUE TITLE
Exception while creating subsequent Camera streaming sessions

### ISSUE THREAD

**Issue by sarathrda** [LogmeinRescue/Android-SDK#11] opened 2018-04-11 07:26 UTC
The `NullPointerException` is observed, when a new session is created and tried to stream from the Android Application, after the Successful first session, without closing the application.

**STEPS TO REPRODUCE**

- Initiate a New Camera Streaming session in Android Application
- Accept the Incoming request in Technician Console
- Observe the camera is being streaming successfully
- Disconnect the session
- Create a new session, and try to connect without closing the Android Application
- Observe that `ConnectedEvent` is received and then the Exception occurs. 

The file is attached [here](https://github.com/LogmeinRescue/Android-SDK/files/1897632/log_me_in_error.txt).

**Comment by tbalogh** [comment] 2018-04-12 09:42
Dear Sarath,

We will review this issue and get in touch with you shortly.

Thank you for bringing this to our attention.

Tamas

**Comment by toga1209** [comment] 2018-04-13 14:37
Hi @sarathrda ,

Though local camera stream rendering works without a connected session when you create a new session then rendering from the previous session should be stopped and the new session object should be used for rendering.
We are going to update our documentation to make it clear.  If this constraint remains in our SDK we are also add an explicit error handling and meaningful exception in our next version.
In the future we try to improve our API to make it more fluent to use and even if this constraint remains in our SDK we are also add an explicit error handling and meaningful exception in our next version.

Based on the stack trace you provided I assume it is the root cause of this issue.

So please make sure that before disposing old session object and creating new session object you stop rendering in the old session:
`CameraStreamingExtension extension = rescueSession.getExtension(CameraStreamingExtension.class);
extension.stopRendering();`

Could you please confirm if rendering of camera stream locally is restarted with second session object after the first session is disconnected in your case?
If it is not yet implemented in that way then could you please try if it works for you?

Thanks in advance for your reply!

**Comment by sarathrda** [comment] 2018-04-16 09:09
Hi @toga1209 ,

I have tried to invoke `stopRendering()` once the Session is disconnected.

It is **WORKING FINE**.

Thanks for the update and also keep us posted about the API updates in the upcoming SDK regarding the above updates regarding Error handling.

Thanks once again.

**Comment by balazsbanyai** [comment] 2018-04-26 11:30
Hello,

I'm closing this, as we've updated the documentation according to this scenario, see the [_Camera streaming/Notes on extension lifecycle_](https://logmeinrescue.github.io/Android-SDK/#12) section, and we opened an issue internally to improve our error handling. 

We really appreciate for bringing this to our attention.

**Closed** 2018-04-26 11:30 UTC
