### ISSUE TITLE
Device screen sharing

### ISSUE THREAD

**Issue by voliverio** [LogmeinRescue/Android-SDK#25] opened 2019-07-19 19:33 UTC
Hi, I'm creating a session factory setting the extension DeviceScreenStreamingExtension, but in the Technician Console I'm only able to chat with the device.

`           
SessionFactory factory = SessionFactory.newInstance();
factory.useExtension(DeviceScreenStreamingExtension.class);
factory.create(getApplicationContext(), apiKey, new SessionFactory.SessionCreationCallback() {
@Override
public void onSessionCreated(Session session) {
                    // The session is now created
                    session.connect(SessionConfig.createWithChannelId(channelId));
                    session.getEventBus().add(new LogMeInEventHandler(mApplication));
                }
});
`

I've included all the dependencies but I can't manage to put it to work, event the dialog that is meant to be shown (https://logmeinrescue.github.io/Android-SDK/#11) is not shown. 

Is there any known issue in using the Android SDK to share the device screen?

I'm trying it in a Samsung J2 with Android 7.1.1.

Thank you.

**Comment by tbalogh** [comment] 2019-07-22 12:57
Hi @voliverio,

We are not aware of any of that kind of issue with sharing the device screen. 

There is a statement about the screen sharing in section https://logmeinrescue.github.io/Android-SDK/#10 that we may didn't emphasize enough:

_To let technicians see App/Device Screen in the Technician Console do either of the following:_

- _Use DeviceInfoExtension_
- _In the Administration Center, turn on Classic display feature_

Can you verify that you did either of the things mentioned above and you still don't see the screen in the technician console?

**Comment by tbalogh** [comment] 2019-07-22 13:02
Hi @voliverio 

We are not aware any of this kind of issue with the screen sharing. We have a statement about screen sharing in the section https://logmeinrescue.github.io/Android-SDK/#10 that we may don't emphasize enough:

> To let technicians see App/Device Screen in the Technician Console do either of the following:
> 
> - Use DeviceInfoExtension
> - In the Administration Center, turn on Classic display feature

Can you verify that you either use the DeviceInfoExtension or turn this feature in the Administration Center and the issue is still present?

Best,
Tamas

**Comment by voliverio** [comment] 2019-07-22 13:09
Hi,

I couldn't find this "Classic display feature" option in Administration Center, where can I find it?

Thank you.

**Comment by tbalogh** [comment] 2019-07-22 13:41
Hi,

I would suggest to verify that screen sharing works as expected by using the DeviceInfoExtension. I think the only thing you need to do is to add one line to your code:

```
SessionFactory factory = SessionFactory.newInstance();
factory.useExtension(DeviceScreenStreamingExtension.class); 
factory.useExtension(DeviceInfoExtension.class); 
factory.create(getApplicationContext(), apiKey, new SessionFactory.SessionCreationCallback() { @Override public void onSessionCreated(Session session) { // The session is now created session.connect(SessionConfig.createWithChannelId(channelId)); session.getEventBus().add(new LogMeInEventHandler(mApplication)); } });
```

Please find more information about the Rescue Technician Console and Administration Center in the [documentation](https://help.logmein.com/pkb_Home?l=en_US&c=products%3Almirescue): 

You may want to check our example apps [here](https://logmeinrescue.github.io/Android-SDK/#18) if you haven't already.

Let us know if screen sharing works for you.

Best,
Tamas

**Comment by voliverio** [comment] 2019-07-22 13:59
Hi Tamas,

After I enable the "Classic display for mobile" in the Administration Center the screen sharing worked just fine!

However, I'm not able to control the remote device, a message in the Technician Console says "Configurations in the remote device are preventing the inicialization of the remote control"

Thank you.

**Comment by tbalogh** [comment] 2019-07-22 14:25
Be aware that you should be able to remotely control only your application and you loose remote control capability when your applications is not in foreground. Is this the use case that you are looking for?

**Comment by voliverio** [comment] 2019-07-22 14:26
Actually I'm not able to control it even when my app is in foreground

**Comment by tbalogh** [comment] 2019-07-22 14:47
@voliverio 

Would you mind to open a ticket with some additional details, especially with device and system information? I close this issue as the sharing of the device screen works.

Best,
Tamas

**Closed by tbalogh** 2019-07-22 14:47 UTC
Labels: awaiting-feedback
