### ISSUE TITLE
App Screen share session goes into the Paused mode

### ISSUE THREAD

**Issue by sarathrda** [LogmeinRescue/Android-SDK#6] opened 2018-03-26 13:19 UTC
Once the App Screen share session has connected and started successfully, and when the app is switched between foreground and background states, the issue occurs.

Below are the steps to Reproduce the Issue:

- From Technician Console, Stop the App Screen Display
- In Mobile, put the app in the background
- From Technician Console, Start the App Screen Display again
- In Mobile, Pull the app from background to foreground
- Now the display in Technician console is still blank, even though the status message `The customer has sent the app to background` has disappeared.
- Now just go back to another activity and suddenly the App Screen is visible in the Technician console.

Herewith I have attached a Video link of the above process:
Link [here](https://rdalabs-my.sharepoint.com/:v:/p/snatesan/EbwKa7iNIL5OnmkVVSybxKsBp_81FE7WO3TjdpL_vcfEHQ?e=iOOph8)

**Comment by balazsbanyai** [comment] 2018-03-29 13:15
Hello, 

We were able to reproduce the bug, and will look into resolving the issue as soon as we can. 

Thank you for bringing this to our attention, Balazs

**Comment by tamasgyongyosi** [comment] 2019-08-06 08:59
Hi @sarathrda ,

We were unable to reproduce this issue with the latest 3.4.0 SDK version. Could you verify that the issue is not existing anymore? If exists please let me know which SDK version.

Thank you very much!

**Comment by sarathrda** [comment] 2019-08-13 06:24
Hello @tamasgyongyosi 

We have verified this issue with the latest SDK and is working as expected.  You can close the same

Thanks,
Sarath

**Comment by tbalogh** [comment] 2019-08-13 14:17
We are happy to hear that @sarathrda !

**Closed by tbalogh** 2019-08-13 14:17 UTC
Labels: awaiting-feedback
